/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    PageFooter: typeof import('./src/components/PageFooter.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    PostItem: typeof import('./src/components/PostItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonItem: typeof import('./src/components/SkeletonItem.vue')['default']
    TaskItem: typeof import('./src/components/TaskItem.vue')['default']
    ToDoCreateModal: typeof import('./src/components/ToDoCreateModal.vue')['default']
    ToDoDeleteModal: typeof import('./src/components/ToDoDeleteModal.vue')['default']
  }
}
